<?xml version="1.0" encoding="UTF-8"?><testrun name="LancamentoServiceTest" project="controlefinanceiro" tests="11" started="11" failures="1" errors="0" ignored="0">
  <testsuite name="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.169">
    <testcase name="naoDeveSalvarUmLancamentoQuandoHouverErroDeValidacao" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.081"/>
    <testcase name="deveAtualizarOStatusDeUmLancamento" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.008"/>
    <testcase name="deveSalvarUmLancamento" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.007"/>
    <testcase name="deveAtualizarUmLancamento" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.006"/>
    <testcase name="deveLancarErroAoTentarDeletarUmLancamentoQueAindaNaoFoiSalvo" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.006"/>
    <testcase name="deveFiltrarLancamentos" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.016"/>
    <testcase name="deveObterUmLancamentoPorId" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.005"/>
    <testcase name="deveDeletarUmLancamento" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.004"/>
    <testcase name="deveRetornarVazioQuandoOLancamnetoNaoExistir" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.003"/>
    <testcase name="deveLancarErroAoTentaAtualizarUmLancamentoQueAindaNaoFoiSalvo" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.003"/>
    <testcase name="deveLancarErrosAoValidarUmLancamento" classname="github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest" time="0.01">
      <failure>java.lang.AssertionError: &#13;
Expecting message:&#13;
 &lt;"Informe uma Descrição válida"&gt;&#13;
but was:&#13;
 &lt;"Informe uma Descrição válida! "&gt;&#13;
	at github.madeoliveira.controlefinanceiro.service.LancamentoServiceTest.deveLancarErrosAoValidarUmLancamento(LancamentoServiceTest.java:154)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
